// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID               uuid.UUID `json:"id"`
	TenantID         uuid.UUID `json:"tenant_id"`
	UsersID          uuid.UUID `json:"users_id"`
	CategoryID       uuid.UUID `json:"category_id"`
	Nome             string    `json:"nome"`
	Fornecedor       string    `json:"fornecedor"`
	Type             string    `json:"type"`
	Value            string    `json:"value"`
	CodigoBarras     string    `json:"codigo_barras"`
	ComprovantePdf   []byte    `json:"comprovante_pdf"`
	PixContaBancaria string    `json:"pix_conta_bancaria"`
	Description      string    `json:"description"`
	Period           string    `json:"period"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	UsersID   uuid.UUID `json:"users_id"`
	Nome      string    `json:"nome"`
	Descricao string    `json:"descricao"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Nome      string    `json:"nome"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Nome      string    `json:"nome"`
	Email     string    `json:"email"`
	Senha     string    `json:"senha"`
	Whatsapp  string    `json:"whatsapp"`
	Foto      []byte    `json:"foto"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
